In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read the dataset
file_path = 'Titanic.csv'
df = pd.read_csv(file_path)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
x = df.drop('Survived', axis=1)
y = df['Survived']

In [3]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [4]:
from sklearn.preprocessing import MinMaxScaler
num_cols = x.select_dtypes('number').columns
scaler = MinMaxScaler()
scaler.fit(x[num_cols])
x[num_cols] = scaler.transform(x[num_cols])

In [5]:
x

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0.000000,1.0,"Braund, Mr. Owen Harris",male,0.271174,0.125,0.000000,A/5 21171,0.014151,NaN,S
1,0.001124,0.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,0.125,0.000000,PC 17599,0.139136,C85,C
2,0.002247,1.0,"Heikkinen, Miss. Laina",female,0.321438,0.000,0.000000,STON/O2. 3101282,0.015469,NaN,S
3,0.003371,0.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,0.125,0.000000,113803,0.103644,C123,S
4,0.004494,1.0,"Allen, Mr. William Henry",male,0.434531,0.000,0.000000,373450,0.015713,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0.995506,0.5,"Montvila, Rev. Juozas",male,0.334004,0.000,0.000000,211536,0.025374,NaN,S
887,0.996629,0.0,"Graham, Miss. Margaret Edith",female,0.233476,0.000,0.000000,112053,0.058556,B42,S
888,0.997753,1.0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,0.125,0.333333,W./C. 6607,0.045771,NaN,S
889,0.998876,0.0,"Behr, Mr. Karl Howell",male,0.321438,0.000,0.000000,111369,0.058556,C148,C
890,1.000000,1.0,"Dooley, Mr. Patrick",male,0.396833,0.000,0.000000,370376,0.015127,NaN,Q

In [21]:
from category_encoders import OneHotEncoder
str_cols = ["Sex", "Embarked"]
encoder = OneHotEncoder(cols = str_cols, drop_invariant=True)
x = encoder.fit_transform(x)

ValueError: X does not contain the columns listed in cols

In [19]:
x

,PassengerId,Pclass,Name_1,Name_2,Name_3,Name_4,Name_5,Name_6,Name_7,Name_8,...,Cabin_143,Cabin_144,Cabin_145,Cabin_146,Cabin_147,Cabin_148,Embarked_1,Embarked_2,Embarked_3,Embarked_4
0,0.000000,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
1,0.001124,0.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0.002247,1.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
3,0.003371,0.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0.004494,1.0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.995506,0.5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
887,0.996629,0.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
888,0.997753,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
889,0.998876,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
890,1.000000,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0